/*
-- Query: SELECT region, `name` as 'name', capital FROM java_backend.countries
LIMIT 0, 1000

-- Date: 2024-06-10 16:27
*/
INSERT INTO `` (regione,name,capital) VALUES ('Asia','Afghanistan','Kabul'),
 ('Europe','Albania','Tirana'),
 ('Africa','Algeria','Algiers'),
 ('Africa','Angola','Luanda'),
 ('Americas','Argentina','Buenos Aires'),
 ('Asia','Armenia','Yerevan'),
 ('Oceania','Australia','Canberra'),
 ('Europe','Austria','Vienna'),
 ('Asia','Azerbaijan','Baku'),
 ('Asia','Bahrain','Manama'),
 ('Asia','Bangladesh','Dhaka'),
 ('Europe','Belarus','Minsk'),
 ('Europe','Belgium','Brussels'),
 ('Americas','Belize','Belmopan'),
 ('Africa','Benin','Porto-Novo'),
 ('Asia','Bhutan','Thimphu'),
 ('Americas','Bolivia (Plurinational State of)','Sucre'),
 ('Europe','Bosnia and Herzegovina','Sarajevo'),
 ('Africa','Botswana','Gaborone'),
 ('Americas','Brazil','Brasília'),
 ('Europe','Bulgaria','Sofia'),
 ('Africa','Burkina Faso','Ouagadougou'),
 ('Africa','Burundi','Gitega'),
 ('Asia','Cambodia','Phnom Penh'),
 ('Africa','Cameroon','Yaoundé'),
 ('Americas','Canada','Ottawa'),
 ('Africa','Cabo Verde','Praia'),
 ('Africa','Central African Republic','Bangui'),
 ('Africa','Chad','N\'Djamena'),
 ('Americas','Chile','Santiago'),
 ('Asia','China','Beijing'),
 ('Americas','Colombia','Bogotá'),
 ('Africa','Comoros','Moroni'),
 ('Africa','Congo','Brazzaville'),
 ('Americas','Costa Rica','San José'),
 ('Europe','Croatia','Zagreb'),
 ('Americas','Cuba','Havana'),
 ('Europe','Cyprus','Nicosia'),
 ('Europe','Czech Republic','Prague'),
 ('Europe','Denmark','Copenhagen'),
 ('Africa','Djibouti','Djibouti'),
 ('Americas','Dominican Republic','Santo Domingo'),
 ('Americas','Ecuador','Quito'),
 ('Africa','Egypt','Cairo'),
 ('Americas','El Salvador','San Salvador'),
 ('Africa','Equatorial Guinea','Malabo'),
 ('Europe','Estonia','Tallinn'),
 ('Africa','Ethiopia','Addis Ababa'),
 ('Oceania','Fiji','Suva'),
 ('Europe','Finland','Helsinki'),
 ('Europe','France','Paris'),
 ('Africa','Gabon','Libreville'),
 ('Asia','Georgia','Tbilisi'),
 ('Europe','Germany','Berlin'),
 ('Africa','Ghana','Accra'),
 ('Europe','Greece','Athens'),
 ('Americas','Guatemala','Guatemala City'),
 ('Africa','Guinea','Conakry'),
 ('Africa','Guinea-Bissau','Bissau'),
 ('Americas','Guyana','Georgetown'),
 ('Americas','Haiti','Port-au-Prince'),
 ('Europe','Vatican City','Vatican City'),
 ('Americas','Honduras','Tegucigalpa'),
 ('Asia','Hong Kong','City of Victoria'),
 ('Europe','Hungary','Budapest'),
 ('Europe','Iceland','Reykjavík'),
 ('Asia','India','New Delhi'),
 ('Asia','Indonesia','Jakarta'),
 ('Africa','Côte d\'Ivoire','Yamoussoukro'),
 ('Asia','Iran (Islamic Republic of)','Tehran'),
 ('Asia','Iraq','Baghdad'),
 ('Europe','Ireland','Dublin'),
 ('Asia','Israel','Jerusalem'),
 ('Europe','Italy','Rome'),
 ('Americas','Jamaica','Kingston'),
 ('Asia','Japan','Tokyo'),
 ('Asia','Jordan','Amman'),
 ('Asia','Kazakhstan','Nur-Sultan'),
 ('Africa','Kenya','Nairobi'),
 ('Asia','Kuwait','Kuwait City'),
 ('Asia','Kyrgyzstan','Bishkek'),
 ('Asia','Lao People\'s Democratic Republic','Vientiane'),
 ('Europe','Latvia','Riga'),
 ('Asia','Lebanon','Beirut'),
 ('Africa','Lesotho','Maseru'),
 ('Africa','Liberia','Monrovia'),
 ('Africa','Libya','Tripoli'),
 ('Europe','Lithuania','Vilnius'),
 ('Europe','Luxembourg','Luxembourg'),
 ('Europe','North Macedonia','Skopje'),
 ('Africa','Madagascar','Antananarivo'),
 ('Africa','Malawi','Lilongwe'),
 ('Asia','Malaysia','Kuala Lumpur'),
 ('Asia','Maldives','Malé'),
 ('Africa','Mali','Bamako'),
 ('Europe','Malta','Valletta'),
 ('Africa','Mauritania','Nouakchott'),
 ('Africa','Mauritius','Port Louis'),
 ('Americas','Mexico','Mexico City'),
 ('Europe','Moldova (Republic of)','Chișinău'),
 ('Asia','Mongolia','Ulan Bator'),
 ('Europe','Montenegro','Podgorica'),
 ('Africa','Morocco','Rabat'),
 ('Africa','Mozambique','Maputo'),
 ('Asia','Myanmar','Naypyidaw'),
 ('Africa','Namibia','Windhoek'),
 ('Asia','Nepal','Kathmandu'),
 ('Europe','Netherlands','Amsterdam'),
 ('Oceania','New Zealand','Wellington'),
 ('Americas','Nicaragua','Managua'),
 ('Africa','Niger','Niamey'),
 ('Africa','Nigeria','Abuja'),
 ('Asia','Korea (Democratic People\'s Republic of)','Pyongyang'),
 ('Europe','Norway','Oslo'),
 ('Asia','Oman','Muscat'),
 ('Asia','Pakistan','Islamabad'),
 ('Americas','Panama','Panama City'),
 ('Oceania','Papua New Guinea','Port Moresby'),
 ('Americas','Paraguay','Asunción'),
 ('Americas','Peru','Lima'),
 ('Asia','Philippines','Manila'),
 ('Europe','Poland','Warsaw'),
 ('Europe','Portugal','Lisbon'),
 ('Asia','Qatar','Doha'),
 ('Europe','Romania','Bucharest'),
 ('Europe','Russian Federation','Moscow'),
 ('Africa','Rwanda','Kigali'),
 ('Americas','Saint Lucia','Castries'),
 ('Africa','Sao Tome and Principe','São Tomé'),
 ('Asia','Saudi Arabia','Riyadh'),
 ('Africa','Senegal','Dakar'),
 ('Europe','Serbia','Belgrade'),
 ('Africa','Seychelles','Victoria'),
 ('Africa','Sierra Leone','Freetown'),
 ('Asia','Singapore','Singapore'),
 ('Europe','Slovakia','Bratislava'),
 ('Europe','Slovenia','Ljubljana'),
 ('Africa','Somalia','Mogadishu'),
 ('Africa','South Africa','Pretoria'),
 ('Asia','Korea (Republic of)','Seoul'),
 ('Africa','South Sudan','Juba'),
 ('Europe','Spain','Madrid'),
 ('Asia','Sri Lanka','Sri Jayawardenepura Kotte'),
 ('Africa','Sudan','Khartoum'),
 ('Americas','Suriname','Paramaribo'),
 ('Africa','Eswatini','Mbabane'),
 ('Europe','Sweden','Stockholm'),
 ('Europe','Switzerland','Bern'),
 ('Asia','Syrian Arab Republic','Damascus'),
 ('Asia','Taiwan','Taipei'),
 ('Asia','Tajikistan','Dushanbe'),
 ('Africa','Tanzania, United Republic of','Dodoma'),
 ('Asia','Thailand','Bangkok'),
 ('Asia','Timor-Leste','Dili'),
 ('Africa','Togo','Lomé'),
 ('Americas','Trinidad and Tobago','Port of Spain'),
 ('Africa','Tunisia','Tunis'),
 ('Asia','Turkey','Ankara'),
 ('Asia','Turkmenistan','Ashgabat'),
 ('Africa','Uganda','Kampala'),
 ('Europe','Ukraine','Kyiv'),
 ('Asia','United Arab Emirates','Abu Dhabi'),
 ('Americas','United States of America','Washington, D.C.'),
 ('Americas','Uruguay','Montevideo'),
 ('Asia','Uzbekistan','Tashkent'),
 ('Americas','Venezuela (Bolivarian Republic of)','Caracas'),
 ('Asia','Vietnam','Hanoi'),
 ('Asia','Yemen','Sana\'a'),
 ('Africa','Zambia','Lusaka'),
 ('Africa','Zimbabwe','Harare');
